#!/bin/bash


wfdb-config --version 2>/dev/null
if [ ${?} != "0"  ] ; then
    #echo "The toolbox is not installed. Downloading the WFDB Toolbox..."
    unzip wfdb-app-toolbox-0-9-6-1.zip
    if [ "$?" != "0" ]
	then
	wget http://physionet.org/physiotools/matlab/wfdb-app-matlab/wfdb-app-toolbox-0-9-6-1.zip
    fi
    mv mcode /data/physionet/mcode
    sudo chmod a+x -R /data/physionet/mcode/
    sudo chmod a+r -R /data/physionet/mcode/
fi

export LD_LIBRARY_PATH=/data/physionet/mcode/nativelibs/linux-amd64/lib64/:$LD_LIBRARY_PATH
export PATH=/data/physionet/mcode/nativelibs/linux-amd64/lib64/:$PATH